### ISSUE TITLE
Cant add extensions from extensions.gnome.org

### ISSUE THREAD

**Issue by felipetux** [89luca89/ansible-fedora-minimal#1]
When you try to install Gnome Shell extensions from extensions.gnome.org using chrome-gnome-shell on Firefox or Chrome, wont install, even wont show an error but if you check with:

journalctl /usr/bin/gnome-shell

This message appears

Jun 19 15:22:09 laptop.local gnome-shell[1778]: Ignoring excess values in shadow definition
Jun 19 15:22:45 laptop.local gnome-shell[1778]: JS ERROR: GLib.SpawnError: Failed to execute child process “unzip” (No such file or directory)
                                                gotExtensionZipFile@resource:///org/gnome/shell/ui/extensionDownloader.js:89:31
                                                _onInstallButtonPressed/<@resource:///org/gnome/shell/ui/extensionDownloader.js:233:13
Jun 19 15:23:42 laptop.local gnome-shell[1778]: JS ERROR: GLib.SpawnError: Failed to execute child process “unzip” (No such file or directory)
                                                gotExtensionZipFile@resource:///org/gnome/shell/ui/extensionDownloader.js:89:31
                                                _onInstallButtonPressed/<@resource:///org/gnome/shell/ui/extensionDownloader.js:233:13

this can be fixed adding unzip to the install packages. This appears in https://extensions.gnome.org/about/

" I'm using GNOME 3. Why can't I install extensions?
...

Some distributions don't quite package GNOME correctly. Make sure that you have the unzip package installed. 

..."

Apart from this, the rest just works perfectly! thanks!

**Comment by 89luca89** [comment]
Fixed, thanks for the report!
