### ISSUE TITLE
Why are you using Net Install ISO instead of Everything ISO?

### ISSUE THREAD

**Issue by kawpii** [89luca89/ansible-fedora-minimal#2]
As you can read [here](https://ask.fedoraproject.org/t/fedora-netinstall-or-everything/5703) net install is for servers, while Everything ISO is for Workstations.

**Comment by 89luca89** [comment]
Package/config wise should not be different in the optics of this project (start from a minimal fedora)

About the defaults for installation you're right, I will change the README to reflect the use of Everything ISO

Thanks!
